
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.7.0
 * Query Engine version: 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
 */
Prisma.prismaVersion = {
  client: "6.7.0",
  engine: "3cff47a7f5d65c3ea74883f1d736e41d68ce91ed"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ClasesScalarFieldEnum = {
  IdClase: 'IdClase',
  FkIdEntrenador: 'FkIdEntrenador',
  FkIdEspacio: 'FkIdEspacio',
  FkIdHorario: 'FkIdHorario',
  NombreC: 'NombreC',
  Descripcion: 'Descripcion'
};

exports.Prisma.ComentariosScalarFieldEnum = {
  IdComentario: 'IdComentario',
  FkIdUsuario: 'FkIdUsuario',
  Comentario: 'Comentario',
  FechaComentario: 'FechaComentario'
};

exports.Prisma.EntrenadoresScalarFieldEnum = {
  IdEntrenador: 'IdEntrenador',
  FkIdUsuario: 'FkIdUsuario',
  Especialidad: 'Especialidad',
  Experiencia: 'Experiencia',
  Telefono: 'Telefono'
};

exports.Prisma.EspaciosScalarFieldEnum = {
  IdEspacio: 'IdEspacio',
  NombreE: 'NombreE',
  Tipo: 'Tipo',
  Capacidad: 'Capacidad',
  Descripcion: 'Descripcion',
  Ubicacion: 'Ubicacion'
};

exports.Prisma.HorariosScalarFieldEnum = {
  IdHorario: 'IdHorario',
  FkIdEspacio: 'FkIdEspacio',
  DiaSemana: 'DiaSemana',
  HoraInicio: 'HoraInicio',
  HoraFin: 'HoraFin'
};

exports.Prisma.InscripcionClasesScalarFieldEnum = {
  IdInscripcionClase: 'IdInscripcionClase',
  FkIdUsuario: 'FkIdUsuario',
  FkIdClase: 'FkIdClase',
  FechaI: 'FechaI'
};

exports.Prisma.InscripcionTorneosScalarFieldEnum = {
  IdInscripcionTorneo: 'IdInscripcionTorneo',
  FkIdUsuario: 'FkIdUsuario',
  FkIdTorneo: 'FkIdTorneo',
  FechaI: 'FechaI'
};

exports.Prisma.ReservasScalarFieldEnum = {
  IdReserva: 'IdReserva',
  FkIdUsuario: 'FkIdUsuario',
  FkIdEspacio: 'FkIdEspacio',
  FechaReserva: 'FechaReserva',
  HoraInicioR: 'HoraInicioR',
  HoraFinR: 'HoraFinR',
  Estado: 'Estado'
};

exports.Prisma.TalleresScalarFieldEnum = {
  IdTaller: 'IdTaller',
  NombreTa: 'NombreTa',
  Descripcion: 'Descripcion',
  FkIdEntrenador: 'FkIdEntrenador',
  FkIdHorario: 'FkIdHorario'
};

exports.Prisma.TorneosScalarFieldEnum = {
  IdTorneo: 'IdTorneo',
  NombreT: 'NombreT',
  FechaInicioT: 'FechaInicioT',
  FechaFinT: 'FechaFinT',
  FkIdEspacio: 'FkIdEspacio',
  FkIdHorario: 'FkIdHorario'
};

exports.Prisma.UsuariosScalarFieldEnum = {
  IdUsuario: 'IdUsuario',
  Usuario: 'Usuario',
  NombreU: 'NombreU',
  CorreoU: 'CorreoU',
  Contrase_a: 'Contrase_a',
  Nivel: 'Nivel',
  FechaRegistro: 'FechaRegistro',
  Telefono: 'Telefono'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.ClasesOrderByRelevanceFieldEnum = {
  NombreC: 'NombreC',
  Descripcion: 'Descripcion'
};

exports.Prisma.ComentariosOrderByRelevanceFieldEnum = {
  Comentario: 'Comentario'
};

exports.Prisma.EntrenadoresOrderByRelevanceFieldEnum = {
  Especialidad: 'Especialidad',
  Experiencia: 'Experiencia',
  Telefono: 'Telefono'
};

exports.Prisma.EspaciosOrderByRelevanceFieldEnum = {
  NombreE: 'NombreE',
  Descripcion: 'Descripcion',
  Ubicacion: 'Ubicacion'
};

exports.Prisma.HorariosOrderByRelevanceFieldEnum = {
  DiaSemana: 'DiaSemana'
};

exports.Prisma.TalleresOrderByRelevanceFieldEnum = {
  NombreTa: 'NombreTa',
  Descripcion: 'Descripcion'
};

exports.Prisma.TorneosOrderByRelevanceFieldEnum = {
  NombreT: 'NombreT'
};

exports.Prisma.UsuariosOrderByRelevanceFieldEnum = {
  Usuario: 'Usuario',
  NombreU: 'NombreU',
  CorreoU: 'CorreoU',
  Contrase_a: 'Contrase_a',
  Telefono: 'Telefono'
};
exports.Espacios_Tipo = exports.$Enums.Espacios_Tipo = {
  deportivo: 'deportivo',
  recreativo: 'recreativo'
};

exports.Reservas_Estado = exports.$Enums.Reservas_Estado = {
  pendiente: 'pendiente',
  confirmada: 'confirmada',
  cancelada: 'cancelada'
};

exports.Usuarios_Nivel = exports.$Enums.Usuarios_Nivel = {
  admin: 'admin',
  entrenador: 'entrenador',
  usuario: 'usuario'
};

exports.Prisma.ModelName = {
  Clases: 'Clases',
  Comentarios: 'Comentarios',
  Entrenadores: 'Entrenadores',
  Espacios: 'Espacios',
  Horarios: 'Horarios',
  InscripcionClases: 'InscripcionClases',
  InscripcionTorneos: 'InscripcionTorneos',
  Reservas: 'Reservas',
  Talleres: 'Talleres',
  Torneos: 'Torneos',
  Usuarios: 'Usuarios'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
